### ISSUE TITLE
Template is broken

### ISSUE THREAD

**Issue by BorisFR** [fehaar/FFWD#11]
Hello. I'm playing since several days with FFWD and it is really a good thing.
I have just refresh with latest source and have now some problem with the template. It is link to other projects (and not the .dll) that is not in the template.
I have try to put FFWD project just near the template folder, but with no luck.

Here the VS solution :
http://twitpic.com/8w4jk3

Here is the output in Vusal Studio :
C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.csproj : error  : Unable to read the project file 'PressPlay.FFWD.csproj'. 
C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.csproj: The project file could not be loaded. Could not find a part of the path 'C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.csproj'.

C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.WP7.csproj : error  : Unable to read the project file 'PressPlay.FFWD.WP7.csproj'. 
C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.WP7.csproj: The project file could not be loaded. Could not find a part of the path 'C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.WP7.csproj'.

C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD.Import\PressPlay.FFWD.Import.csproj : error  : Unable to read the project file 'PressPlay.FFWD.Import.csproj'. 
C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD.Import\PressPlay.FFWD.Import.csproj: The project file could not be loaded. Could not find a part of the path 'C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD.Import\PressPlay.FFWD.Import.csproj'.

C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.X360.csproj : error  : Unable to read the project file 'PressPlay.FFWD.X360.csproj'. 
C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.X360.csproj: The project file could not be loaded. Could not find a part of the path 'C:\Unity3D\NewTest\FFWD\Framework\PressPlay.FFWD\PressPlay.FFWD.X360.csproj'.

**Comment by BorisFR** [comment]
Forget about it !
Sorry.

I have not put the FFWD in the right place. It is now ok.

**Comment by fehaar** [comment]
Cool. You can also just change the references to the FFWD projects in the solution. Once you have your XNA project up nad running there is really no need to update the template from Git anyway. It is just a helper to make it easy to get started.

**Comment by cauerego** [comment]
Boris, by this you basically mean there's a step missing in the Getting Started Guide, right?

The Getting the template "step 0" says to get the FFWD Template (and provides a link) and talks about how it's wired at "this project" as a "submodule". But that's far from clear it means we should get FFWD project and add it into the empty folder from the Template. At least for me, who had no idea what submodule really meant there ( http://help.github.com/submodules/ ).

Also I'd rename the whole "Getting the template" section into "Testing the template" and reformulate that first paragraph, or replace the sentence "Test that the template is working in the following way:" by another section title: "Testing the template", thus giving much more emphasis to the "Getting the template" section.

By the way, since this is my first post around here: Great stuff there, fehaar! Thanks for sharing it! :-)

**Comment by fehaar** [comment]
I am glad you like it. I will take a look at improving the wording so it is easier to use. Thanks for the suggestions.

**Comment by cauerego** [comment]
Well, in the end, after little more than 1 day fighting to I finally compile the template, I had many, many issues ("compile" errors) with our project (which is supposed to be actually pretty simple) and since we don't reaaaaally need this running on windows phone for now, I had to give up. But it was a fun run and good stuff nevertheless. Thanks for the ride! ;-)

**Comment by fehaar** [comment]
Too bad about the compile errors. Was it due to missing features in FFWD or something else? That said. Getting your Unity project to work properly in XNA will take some work. It is not just compile and run, unfortunately.

**Comment by cauerego** [comment]
The project is in fact quite complex so it was probably missing features, from the little I can tell. I didn't get too deep into FFWD: I haven't read the code, I don't even know exactly what it is doing... From the wiki features page I figured it could work. Only thing on the "not supported" list we'd need was coroutines (for loading bars), and the list is 18 days old. But there are also somethings not listed there at all, and I later saw under Issues as open, such as alpha test effect, for whatever that means, and we do use alpha'ed shaders, so then I figure there might be many more minor features missing on FFWD.

If it helps knowing a little more about our project, I dream to one day open at least part of it because it is essentially a "FBX player" to play stuff we already have for VRML / X3D. In a way as similar as possible. Everything else it has is just a wrapper around that, such as being able to download models.
