### ISSUE TITLE
Automatically add new GOs to current scene.

### ISSUE THREAD

**Issue by Cookingsource** [fehaar/FFWD#15]
From what i've experimented, it seems that new created GameObjects are not included automatically in the current scene(when created in runtime), this could be an issue for people that use scripts that rely on this behavior.

**Comment by fehaar** [comment]
They are added to the objects pool and are available there, if that is what you mean. When you create a new GO at runtime it will automatically get a new transform that will get registered - which will also register the GO.

How are you testing for the existance of the GO? Because there is one missing piece of functionality that is not present that might bite you here.

In Unity you can test if an Object exists by doing obj == null. At the moment this does not work in FFWD and will produce the default == null behaviour. You can do (bool)obj - which also works in Unity instead.

I discovered the null-comparison functionality quite late, and tried to implement it - but the amount of internal errors that this produced were so massive so the attempt was abandoned. I have been reconsidering it again of late, because I considered that it can actually be used actively to make a lot of the internal code much leaner.

So. If this is what you experience, I will change the issue text to be that. If not - I need more info to find out what your problem is.

**Comment by Cookingsource** [comment]
Ok, it seems i misunderstood how the framework works, what i made was watch the scene var Application has, after its loaded. I create the gameobject and watch it again. So i expected the current scene to have an extra gameobject inside but, it didn't show the gameobject in the scene object so i thought it was not included. 

But after reading the Application class more in depth it seems you don't use directly the scene class but a dictionary in the Application class, so that list is "the current scene". The created object is contained in that dictionary as expected.

Thanks for the help.

**Comment by fehaar** [comment]
Yes. Unity has no notion of "current scene" anyway. It just have objects that are alive. So the scene class is just a placeholder to read stuff in via XML. Nothing more. Actually I have no clue why the scene is not set to null after load is finished. It is a lot of wasted memory right there. I will look into that instead. :)

**Comment by Cookingsource** [comment]
Good, I'll also do it locally. There's a call to garbage collection inside the initializer of the scene. But i think the forced garbage collection should be executed after the method call, also after making the scene null. I really don't know a way to measure the memory retained by some instance, but it could be useful in a lot of scenarios.

**Comment by fehaar** [comment]
It is. I have placed the "= null" just after the Initialize call. But after that, separate assets like meshes, textures and animations are loaded. The forced garbage call is done after all assets have loaded because that creates a lot of garbage that has to go. I used some different profiler tools to monitor memory when we optimized Tentacles. At that point the framework created almost no garbage at all during gameplay. On most levels you can play ~3 mins before a collection is triggered - and none of the garbage was made in the framework. That has probably changed now as there are a lot of changes in the core. But I will do a similar session with the current framework at some point. Apart from that we did not use much memory even though most of the textures in the game is pre-loaded and available all the time. You have a 90MB memory cap on the Phone and we were way below that.
