### ISSUE TITLE
GetButton(string)': not all code paths return a value

### ISSUE THREAD

**Issue by bigdaddio** [fehaar/FFWD#36]
I do not know if this is because I have the latest WP7 update or not, but I get 3 errors:

'PressPlay.FFWD.Input.GetButton(string)': not all code paths return a value
'PressPlay.FFWD.Input.GetButtonUp(string)': not all code paths return a value
'PressPlay.FFWD.Input.GetButtonDown(string)': not all code paths return a value
they are all in PressPlay.FFWD.WP7

I am using WP SDK 7.1.1 if that makes any difference.

**Comment by Elideb** [comment]
The code for GetButton was not tested for WP7 builds. Sorry. However, it is easily fixed. You just need to check if the button is "Back" and return the corresponding value of GetKey(KeyCode.Back). If the text is not "Back", just return false.
If you fix this issue, feel free to create a pull request. Otherwise, I'll code the fix and request Feehar to integrate it.

**Comment by fehaar** [comment]
I have just pushed a fix. Thanks for the heads up bigdaddio.

**Comment by bigdaddio** [comment]
Thanks for getting on that so quickly, The weekend is coming!

**Comment by fehaar** [comment]
I hope you can put it to good use then. :)

## 

Thomas Gravgaard
Senior Software Developer
Press Play ApS
thomas@pressplay.dk
+45 26 74 26 74
