### ISSUE TITLE
no Character Controller?

### ISSUE THREAD

**Issue by alfiolocastro** [fehaar/FFWD#51]
I was doing some experimental ports to understand how this awesome framework works and I noticed that it does not have the Character Controller script (that is embedded in Unity). Is this exact or am I doing it wrong?

**Comment by fehaar** [comment]
You are not doing anything wrong. The CharacterController has not been ported yet.

**Comment by schuranator** [comment]
Do you have a sample code how to move a model around if we assign it a rigid body? I'm stuck on how to setup/config controllers. I'm hoping to port to xna xbox but even to just test with keyboard would be nice.

**Comment by fehaar** [comment]
If you assign a rigidbody to an object, it is usually because you want physics to move it around. It can be done by moving the gameobject in FixedUpdate though.

But it also sounds like you need help on just getting input? If that is correct, take a look at the Input class. Unity doc here: http://docs.unity3d.com/Documentation/ScriptReference/Input.html
